name: solid_software_recruitment_task
description: "Flutter app for Solid Software recruitment task"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

  solid_lints: ^0.3.0

flutter:
  uses-material-design: true
